name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      # ✅ Run only unit tests in CI (skip Playwright / E2E)
      - name: Test (unit only)
        run: npm run test:unit

      - name: Build
        run: npm run build

      # Optional — keep Playwright report upload for local or future CI runs
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: apps/web/playwright-report
          if-no-files-found: ignore
